export const langauges = {
  en: {
    // browse
    home: "Home",
    tvshow: "TV Show",
    movies: "Movies",
    new_and_popular: "New & Popular",
    mylist: "My List",
    browsebylanguage: "Browse by Language",
    profile: "Profile",
    signout: "SignOut",
    nowplayingmovies: "Now Playing Movies",
    toppopular: "Top Popular",
    search: "Search",
    comming_soon: "Comming Soon",
    download: "Download",
    more: "More",
    play: "Play",
    more_info: "More Info",

    // SignIn-SingOut
    signinheader: "SIGN IN",
    signoutheader: "SIGN UP",
    signinbutton: "Sign-In",
    signupbutton: "Sign-Up",
    or: "OR",
    use_a_sign_code: "Use a sign-in code",
    remember_me: "Remember me",
    new_to_netflix: "New to netflix",
    forgot_password: "Forgot password",
    email_placeholder: "Email",
    password_placeholder: "Password",
    name_placeholder: "Name",
    sign_up_now: "Sign up now",

    // Search Movies
    search_placeholder: "Search for a show, Movies,gener... etc",
    top_searches: "Top Searches",

    // Footer
    audio_description: "Audio Description",
    investore_relations: "Investore Relations",
    privacy: "Privacy",
    contact_us: "Contact Us",
    help_center: "Help Center",
    jobs: "Jobs",
    legal_notices: "Legal Notices",
    do_not_sell_or_share_my_personal_information:
      "Do Not Sell or Share My Personal Information",
    gift_cards: "Gift Cards",
    netfli_shop: "Netflix shop",
    cookies_prefernces: " Cookies Prefernces",
    add_choices: "Add Choices",
    media_center: "Media Center",
    terms_of_use: "Terms of Use",
    corporate_information: "Corporate Information",
    preview: "Preview",

    // Movies Tv Page
    airing_today: "Airing Today",
    on_the_air: "On the Air",
    popular: "Popular",
    top_rated: "Top Rated",
    upcoming: "Up Coming",
  },
  hi: {
    // browse
    home: "मुखपृष्ठ",
    tvshow: "टीवी शो",
    movies: "फिल्मों",
    new_and_popular: "नया & लोकप्रिय",
    mylist: "मेरी सूची",
    browsebylanguage: "भाषा के आधार पर ब्राउज़ करें",
    profile: "ख़ाका",
    signout: "साइन आउट",
    nowplayingmovies: "अभी फ़िल्में चल रही हैं",
    toppopular: "शीर्ष लोकप्रिय",
    search: "खोज",
    comming_soon: "जल्द आ रहा है",
    download: "डाउनलोड",
    more: "अधिक",
    play: "प्ले करा",
    more_info: "अधिक माहिती",

    // Sign-in-sign-out
    signinheader: "साइन इन करें",
    signoutheader: "नाम लिखो",
    signinbutton: "साइन इन करें",
    or: "नहीं तो",
    use_a_sign_code: "साइन-इन कोड का उपयोग करें",
    remember_me: "मुझे याद रखना",
    new_to_netflix: "नेटफ्लिक्स के लिए नया",
    forgot_password: "पासवर्ड भूल गए",
    email_placeholder: "ईमेल",
    password_placeholder: "पासवर्ड",
    name_placeholder: "नाम",
    sign_up_now: "साइन अप करें",

    // Search Movies
    search_placeholder: "कोई शो, फ़िल्में, सामान्य... आदि खोजें",
    top_searches: "शीर्ष खोजें",

    // Footer
    audio_description: "ऑडियो विवरण",
    investore_relations: "निवेशक संबंध",
    privacy: "गोपनीयता",
    contact_us: "संपर्क करें",
    help_center: "सहायता केंद्र",
    jobs: "नौकरियों",
    legal_notices: "कानूनी नोटिस",
    do_not_sell_or_share_my_personal_information:
      "मेरी व्यक्तिगत जानकारी न बेचें या साझा न करें",
    gift_cards: "उपहार कार्ड",
    netfli_shop: "नेटफ्लिक्स शॉप",
    cookies_prefernces: " कुकीज़ प्राथमिकता",
    add_choices: "विकल्प जोड़ें",
    media_center: "मीडिया सेंटर",
    terms_of_use: "उपयोग की शर्तें",
    corporate_information: "कॉर्पोरेट जानकारी",
    preview: "पूर्वावलोकन",

    // movies & TV
    airing_today: "आज प्रसारित हो रहा है",
    on_the_air: "ऑन एयर ",
    popular: "लोकप्रिय",
    top_rated: "टॉप रेटेड",
    upcoming: "आने वाली ",
  },
};
